# Only exmaple
parameters:
    # Defines execution schedule
    atoolo.crawler.schedule: 
        - '30 2 * * *'

    # Status codes that trigger retries
    atoolo.crawler.retry_status_codes:
        - 408
        - 429
        - 500
        - 501
        - 502
        - 503
        - 504