# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(DEFAULT_URI): 'https://localhost'
services:
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ["command"]

    Atoolo\Crawler\:
        resource: "../src/"

    # Run in Development
    Atoolo\Crawler\Command\Index:
        arguments:
            $indexerConfigurationLoader: '@atoolo_search.indexer.configuration_loader'

    # Run in Customer Projekt
    Atoolo\Crawler\Application\Schedule:
        arguments:
            $schedule: "%atoolo.crawler.schedule%"

    Atoolo\Crawler\Application\StartCrawlerMessageHandler:
        arguments:
            $indexerConfigurationLoader: '@atoolo_search.indexer.configuration_loader'

    Atoolo\Crawler\Domain\Crawler\Ports\RequestExecutor:
        arguments:
            $retryStatusCodes: "%atoolo.crawler.retry_status_codes%"

    Atoolo\Crawler\Controller\CrawlerManager:
        arguments:
            $urlCollector: '@Atoolo\Crawler\Domain\Crawler\Steps\URLCollector'
            $fetcher: '@Atoolo\Crawler\Domain\Crawler\Steps\Fetcher'
            $processor: '@Atoolo\Crawler\Domain\Crawler\Steps\Processor'
            $logger: "@logger"
            $indexer: '@Atoolo\Crawler\Domain\Crawler\Steps\Indexer'

    Atoolo\Crawler\Domain\Crawler\Ports\RequestExecutorInterface: '@Atoolo\Crawler\Domain\Crawler\Ports\RequestExecutor'

    # gehört eigentlich ins Kunden-FEDS bzw. Commons-FEDS
    Atoolo\Crawler\Domain\Crawler\Steps\Indexer:
        arguments:
            $indexService: "@atoolo_search.indexer.solr_index_service"
            $progressHandler: "@atoolo_search.indexer.internal_resource_progress_state"